In [95]:
import pandas as pd  
import numpy as np 
import matplotlib as plt
pd.set_option("display.max_columns", None)

df = pd.read_csv('insurance claims data.csv')

In [96]:
df.columns

Index(['Unnamed: 0', 'subscription_length', 'vehicle_age', 'customer_age',
       'region_code', 'region_density', 'segment', 'model', 'fuel_type',
       'max_torque', 'max_power', 'engine_type', 'airbags', 'is_esc',
       'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'steering_type', 'turning_radius', 'length',
       'width', 'gross_weight', 'is_front_fog_lights', 'is_rear_window_wiper',
       'is_rear_window_washer', 'is_rear_window_defogger', 'is_brake_assist',
       'is_power_door_locks', 'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'claim_status'],
      dtype='object')

In [97]:
df.head()

,Unnamed: 0,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,rear_brakes_type,displacement,cylinder,transmission_type,steering_type,turning_radius,length,width,gross_weight,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,97.89bhp@3600rpm,i-DTEC,2,No,Yes,No,Yes,Yes,Drum,1498,4,Manual,Electric,4.9,3995,1695,1051,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,113.45bhp@4000rpm,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,Power,4.6,3445,1515,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,88.77bhp@4000rpm,1.5 Turbocharged Revotorq,2,No,Yes,No,Yes,No,Drum,1497,4,Manual,Electric,5.0,3990,1755,1490,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0

In [98]:
def overview(df):
    df.drop('Unnamed: 0', axis = 1, inplace=True)
    
    return print(df.shape), print(df.info()), print(df[["fuel_type", "max_power", "max_torque", "engine_type"]].nunique()), print(df[["fuel_type", "max_power", "max_torque", "engine_type"]].isnull().sum()),print(df.nunique()), print(df.describe())
overview(df)

(58592, 40)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 40 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   subscription_length               58592 non-null  float64
 1   vehicle_age                       58592 non-null  float64
 2   customer_age                      58592 non-null  int64
 3   region_code                       58592 non-null  object
 4   region_density                    58592 non-null  int64
 5   segment                           58592 non-null  object
 6   model                             58592 non-null  object
 7   fuel_type                         58592 non-null  object
 8   max_torque                        58592 non-null  object
 9   max_power                         58592 non-null  object
 10  engine_type                       58592 non-null  object
 11  airbags                           58592 non-null  int64
 12  is_esc                            58592 non-null  object
 13  is_adjustable_steering            58592 non-null  object
 14  is_tpms                           58592 non-null  object
 15  is_parking_sensors                58592 non-null  object
 16  is_parking_camera                 58592 non-null  object
 17  rear_brakes_type                  58592 non-null  object
 18  displacement                      58592 non-null  int64
 19  cylinder                          58592 non-null  int64
 20  transmission_type                 58592 non-null  object
 21  steering_type                     58592 non-null  object
 22  turning_radius                    58592 non-null  float64
 23  length                            58592 non-null  int64
 24  width                             58592 non-null  int64
 25  gross_weight                      58592 non-null  int64
 26  is_front_fog_lights               58592 non-null  object
 27  is_rear_window_wiper              58592 non-null  object
 28  is_rear_window_washer             58592 non-null  object
 29  is_rear_window_defogger           58592 non-null  object
 30  is_brake_assist                   58592 non-null  object
 31  is_power_door_locks               58592 non-null  object
 32  is_central_locking                58592 non-null  object
 33  is_power_steering                 58592 non-null  object
 34  is_driver_seat_height_adjustable  58592 non-null  object
 35  is_day_night_rear_view_mirror     58592 non-null  object
 36  is_ecw                            58592 non-null  object
 37  is_speed_alert                    58592 non-null  object
 38  ncap_rating                       58592 non-null  int64
 39  claim_status                      58592 non-null  int64
dtypes: float64(3), int64(10), object(27)
memory usage: 17.9+ MB
None
fuel_type       3
max_power       9
max_torque      9
engine_type    11
dtype: int64
fuel_type      0
max_power      0
max_torque     0
engine_type    0
dtype: int64
subscription_length                 140
vehicle_age                          49
customer_age                         41
region_code                          22
region_density                       22
segment                               6
model                                11
fuel_type                             3
max_torque                            9
max_power                             9
engine_type                          11
airbags                               3
is_esc                                2
is_adjustable_steering                2
is_tpms                               2
is_parking_sensors                    2
is_parking_camera                     2
rear_brakes_type                      2
displacement                          9
cylinder                              2
transmission_type                     2
steering_type                         3
turning_radius                        9
length                                9
width                                10
gross_weight                         10
is_front_fog_lights                   2
is_rear_window_wiper                  2
is_rear_window_washer                 2
is_rear_window_defogger               2
is_brake_assist                       2
is_power_door_locks                   2
is_central_locking                    2
is_power_steering                     2
is_driver_seat_height_adjustable      2
is_day_night_rear_view_mirror         2
is_ecw                                2
is_speed_alert                        2
ncap_rating                           5
claim_status                          2
dtype: int64
       subscription_length   vehicle_age  customer_age  region_density  \
count         58592.000000  58592.000000  58592.000000    58592.000000
mean              6.111688      1.388473     44.823935    18826.858667
std               4.142790      1.134413      6.935604    17660.174792
min               0.000000      0.000000     35.000000      290.000000
25%               2.100000      0.400000     39.000000     6112.000000
50%               5.700000      1.200000     44.000000     8794.000000
75%              10.400000      2.200000     49.000000    27003.000000
max              14.000000     20.000000     75.000000    73430.000000

            airbags  displacement      cylinder  turning_radius        length  \
count  58592.000000  58592.000000  58592.000000    58592.000000  58592.000000
mean       3.137066   1162.355851      3.626963        4.852893   3850.476891
std        1.832641    266.304786      0.483616        0.228061    311.457119
min        1.000000    796.000000      3.000000        4.500000   3445.000000
25%        2.000000    796.000000      3.000000        4.600000   3445.000000
50%        2.000000   1197.000000      4.000000        4.800000   3845.000000
75%        6.000000   1493.000000      4.000000        5.000000   3995.000000
max        6.000000   1498.000000      4.000000        5.200000   4300.000000

              width  gross_weight   ncap_rating  claim_status
count  58592.000000  58592.000000  58592.000000  58592.000000
mean    1672.233667   1385.276813      1.759950      0.063968
std      112.089135    212.423085      1.389576      0.244698
min     1475.000000   1051.000000      0.000000      0.000000
25%     1515.000000   1185.000000      0.000000      0.000000
50%     1735.000000   1335.000000      2.000000      0.000000
75%     1755.000000   1510.000000      3.000000      0.000000
max     1811.000000   1720.000000      5.000000      1.000000

(None, None, None, None, None, None)

In [ ]:
def preprocess_data(df):
    df['torque_nm'] = df['max_torque'].str.extract(r'(\d+\.?\d*)Nm').astype(float)
    df['torque_rpm'] = df['max_torque'].str.extract(r'@(\d+)rpm').astype(float)
    
    # Extract Power (bhp and RPM)
    df['power_bhp'] = df['max_power'].str.extract(r'(\d+\.?\d*)bhp').astype(float)
    df['power_rpm'] = df['max_power'].str.extract(r'@(\d+)rpm').astype(float)

    df.drop(['max_torque', 'max_power'], axis=1, inplace=True)
    
    return df

def feature_eng(df):
    # Power-to-weight ratio (very useful in insurance risk modeling)
    df['power_to_weight'] = df['power_bhp'] / df['gross_weight']

    # Torque per liter (engine efficiency indicator)
    df['torque_per_liter'] = df['torque_nm'] / (df['displacement'] / 1000)

    # RPM difference (how peaky the engine is)
    df['rpm_diff'] = df['power_rpm'] - df['torque_rpm']

    return df


    

df = preprocess_data(df)
df = feature_eng(df)

KeyError: 'power_bhp'

In [ ]:
df

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,rear_brakes_type,displacement,cylinder,transmission_type,steering_type,turning_radius,length,width,gross_weight,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,torque_nm,torque_rpm,power_bhp,power_rpm
0,9.3,1.2,41,C8,8794,C2,M4,Diesel,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,250.0,2750.0,113.45,4000.0
1,8.2,1.8,35,C2,27003,C1,M9,Diesel,i-DTEC,2,No,Yes,No,Yes,Yes,Drum,1498,4,Manual,Electric,4.9,3995,1695,1051,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0,200.0,1750.0,97.89,3600.0
2,9.5,0.2,44,C8,8794,C2,M4,Diesel,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,250.0,2750.0,113.45,4000.0
3,5.2,0.4,44,C10,73430,A,M1,CNG,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,Power,4.6,3445,1515,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0,60.0,3500.0,40.36,6000.0
4,10.1,1.0,56,C13,5410,B2,M5,Diesel,1.5 Turbocharged Revotorq,2,No,Yes,No,Yes,No,Drum,1497,4,Manual,Electric,5.0,3990,1755,1490,No,No,No,No,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0,200.0,3000.0,88.77,4000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,10.6,2.6,48,C5,34738,B2,M6,Petrol,K Series Dual jet,2,No,Yes,No,Yes,No,Drum,1197,4,Manual,Electric,4.8,3845,1735,1335,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0,113.0,4400.0,88.50,6000.0
58588,2.3,2.2,37,C3,4076,C2,M4,Diesel,1.5 L U2 CRDi,6,Yes,Yes,Yes,Yes,Yes,Disc,1493,4,Automatic,Power,5.2,4300,1790,1720,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0,250.0,2750.0,113.45,4000.0
58589,6.6,2.2,35,C8,8794,B2,M6,Petrol,K Series Dual jet,2,No,Yes,No,Yes,No,Drum,1197,4,Manual,Electric,4.8,3845,1735,1335,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0,113.0,4400.0,88.50,6000.0
58590,4.1,3.6,44,C8,8794,B2,M6,Petrol,K Series Dual jet,2,No,Yes,No,Yes,No,Drum,1197,4,Manual,Electric,4.8,3845,1735,1335,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0,113.0,4400.0,88.50,6000.0
58591,3.1,0.4,49,C12,34791,B2,M6,Petrol,K Series Dual jet,2,No,Yes,No,Yes,No,Drum,1197,4,Manual,Electric,4.8,3845,1735,1335,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0,113.0,4400.0,88.50,6000.0